### PR TITLE
Dg/rn 0.59 fixes

### PR DESCRIPTION
**Pull request by Dimon70007**
Hi. I have refactored Pincode to use defaultProps and fixed some styling bugs
But i have not much time to test all functionality.
Also i couldn't compose typescript with defaultProps and "strict" enabled, that's why i've disabled strict

### CODE REVIEW

**Comment by galimpian** [comment]
@Haskkor can we get this or my pr merged in?

**Comment by Dimon70007** [comment]
@Haskkor, It will be better to wait until react-native-touch-id will fix it's android build.gradle file

**Comment by galimpian** [comment]
@Dimon70007 does your pr fix the custom icons not showing up as well? I have that as an open issue after I requested and sent in a pr to allow for custom icons.

**Comment by Dimon70007** [comment]
@galimpian, i don't use custom icons in my project and don't know if it works. You can try it and give feedback.
In project i use custom styling and colors for react-native-pincode

**Comment by Haskkor** [comment]
Hi @Dimon70007 ,
Thanks for that :).
Are you saying that I shouldn't merge this yet?
Cheers

**Comment by Dimon70007** [comment]
Hi @Haskkor,
the latest version of react-native-touch-id is broken because of [this commit](https://github.com/naoufal/react-native-touch-id/commit/ccd214802d5c77aa9f215e1c47297e4ffb824a4e), as workaround i have used in my fork react-native-touch-id with [previous commit](https://github.com/naoufal/react-native-touch-id.git#83d18af151be661e54149509b062a6ad06820eab), but i guess this is not an option for production release of any library.
anyway, if you would like, you can merge this PR and add older version of react-native-touch-id library for release

**Pull request closed without merging**
